# Generated by Django 3.2.10 on 2022-04-05 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=20)),
                ('buyer_mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(default=2022, max_length=4)),
                ('Condition', models.CharField(default='Good', max_length=10)),
                ('asking_pricce', models.FloatField(default=15000, max_length=7)),
            ],
        ),
    ]
