# Generated by Django 3.2.10 on 2022-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbuyer',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
