# Generated by Django 3.2.10 on 2022-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0002_alter_carbuyer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuyer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
