# Generated by Django 3.2.10 on 2022-04-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0004_rename_condition_carbuyer_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbuyer',
            name='asking_pricce',
        ),
    ]
