# Generated by Django 3.2.10 on 2022-04-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0005_remove_carbuyer_asking_pricce'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuyer',
            name='asking_pricce',
            field=models.CharField(default=15000, max_length=7),
        ),
    ]
