# Generated by Django 3.2.10 on 2022-04-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0006_carbuyer_asking_pricce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbuyer',
            name='asking_pricce',
        ),
    ]
