# Generated by Django 3.2.10 on 2022-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0007_remove_carbuyer_asking_pricce'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbuyer',
            name='asking_price',
            field=models.CharField(default=15000, max_length=7),
        ),
    ]
