# Generated by Django 3.2.10 on 2022-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_buy', '0008_carbuyer_asking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbuyer',
            name='asking_price',
            field=models.CharField(default=15000, max_length=12),
        ),
    ]
