# Generated by Django 3.2.10 on 2022-04-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carseller',
            old_name='seller_mobile',
            new_name='saler_mobile',
        ),
        migrations.RenameField(
            model_name='carseller',
            old_name='seller_name',
            new_name='saler_name',
        ),
    ]
