# Generated by Django 3.2.10 on 2022-04-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_sale', '0002_auto_20220401_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarSeller',
            new_name='CarSaler',
        ),
    ]
