# Generated by Django 3.2.10 on 2022-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sale', '0004_alter_carsaler_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsaler',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
