# Generated by Django 3.2.10 on 2022-04-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_sale', '0005_carsaler_is_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsaler',
            old_name='Condition',
            new_name='condition',
        ),
    ]
