# Generated by Django 3.2.10 on 2022-04-08 04:27

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('car_sale', '0006_rename_condition_carsaler_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsaler',
            name='asking_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', error_messages={'message': 'price should be less than 100000 & greater than 1000.'}, max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(djmoney.money.Money(1000, 'USD')), djmoney.models.validators.MaxMoneyValidator(djmoney.money.Money(100000, 'USD'))]),
        ),
    ]
